global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: "inference-api"
    static_configs:
      - targets:
          - inference-api:8000
    metrics_path: /metrics
